### PR TITLE
Configuration improvements

### PR DESCRIPTION
**Pull request by Manu343726**
This PR implements improvements in the Standardese configuration to make it as user friendly as possible.
(Note is a WIP). My goals:
- [x] **Disable unit tests by default**: Building tests makes sense for developers only, so the default behavior should be to build the tool (And install it afterwards).
- [x] **Verbose config**: A verbose configuration option to aid with config development.
- [ ] **Libclang setup automation**: See [`cmake/libclang.cmake`](https://github.com/Manu343726/siplasplas/blob/master/cmake/libclang.cmake) and [`3rdParty/standardese/CMakeLists.txt`](https://github.com/Manu343726/siplasplas/blob/master/3rdParty/standardese/CMakeLists.txt). Since both standardese and siplasplas have a very similar libclang config, my end goal would be to move all the libclang configuration scripts to an isolated lib that could be shared and maintained by us. Also, as part of this task I'm thinking about writing a `FindLibClang.cmake` script. The best alternatives I have found are [from rtags](https://github.com/Andersbakken/rtags/blob/master/cmake/FindLibClang.cmake) (GPL though) and [from irony-mode](https://github.com/Sarcasm/irony-mode/blob/master/server/cmake/modules/FindLibClang.cmake) (Which I'm currently using in siplasplas).

### CODE REVIEW

**Comment by foonathan** [comment]
Just fyi: Appveyor is currently broken due to a segfault in the tests. Haven't found the time to look into that yet.

**Comment by foonathan** [comment]
Okay, the Appveyor issues are now fixed. Can we retrigger the CI checks somehow?

**Comment by foonathan** [comment]
A minor thing: Could you move the verbose output to external/external.cmake after it has found all the libclang stuff?

Then you can also extend it for the other dependencies found there.

**Comment by foonathan** [comment]
Any chance you'll finish working on it? :D

**Comment by Manu343726** [comment]
@foonathan well, that depends on what thing do you want to integrate ;)

If you check the siplasplas releases, what it does is to provide a `cmake/` folder in the package containing all the scripts. Then the user just bootstraps siplasplas by downloading the package, extracting it, and `include()`ing those scripts.

The scripts currently do:

 - Figure out libclang version from clang installation
 - Figure out libclang includes
 - Figure out libclang system includes
 - Download libclang (llvm + clang) release and configure everything from it (Optional)

Sorry for the delay :(

**Comment by foonathan** [comment]
I have a bash script: https://github.com/foonathan/standardese/blob/master/travis_get_standardese.sh
It does exactly that.

Might be useful to migrate that to CMake.

**Pull request closed without merging**
