### PR TITLE
Fix rendering issues in README

### PR DESCRIPTION
**Pull request by vitaut**
Started looking into using standardese for my own projects and here's a little PR that fixes trivial issues in `README` that I've discovered while reading it.

### CODE REVIEW

**Comment by foonathan** [comment]
Wait, that's auto generated, so the bug is also in the standardese code.

I was using double backticks or what they are called because I've heard they were better, but apparently not supported...

Could you also fix it in output.cpp in the definition of `write_begin()`? Just write a single backtick there instead of two.

**Comment by vitaut** [comment]
Done (but not sure how to test it yet). Where is the source of README BTW?

**Comment by foonathan** [comment]
(There are no tests for the output yet)
(There is no source yet, I copy paste stuff because the so called chapter mode where you write stuff and include output isn't implemented yet)

**Comment by foonathan** [comment]
Oh, btw: you call `write_str()`, should use `write_char()`.

**Comment by vitaut** [comment]
Oops, should be fixed now.

**Comment by foonathan** [comment]
I'll merge your PRs tomorrow.

**Pull request merged**
