### PR TITLE
Fix warnings and errors on MSVC

### PR DESCRIPTION
**Pull request by mkurdej**
Some fixes to ease the development on MSVC.

### CODE REVIEW

**Comment by foonathan** [comment]
Thanks, haven't setup CI yet.

**Comment by foonathan** [comment]
@mkurdej I'm currently trying to setup Appveyor but I'll get the following error message when building:

LINK : fatal error LNK1104: cannot open file 'libboost_wave-vc140-mt-gd-1_61.lib'
LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc140-mt-gd-1_61.lib'

Do you know what's wrong?

**Comment by mkurdej** [comment]
I think that there's a problem in CMake configuration and standardese tries to link with dynamic libraries (named without 'lib' prefix on windows, e.g. boost_wave-vc140-mt-gd-1_61.lib), but the auto-link mechanism in boost (which seems to be enabled) tries to link with static libraries (with 'lib' prefix), for the moment, I fixed these manually in my MSVC project but I'm trying to prepare a clean CMake fix.

I'll contact you (or create a PR) ASAP.

**Comment by foonathan** [comment]
I somehow managed it as well with:
```
cmake -G"Visual Studio 14 2015 Win64" -DLIBCLANG_LIBRARY="C:\Program Files\LLVM\lib\libclang.lib" -DLIBCLANG_SYSTEM_INCLUDE_DIR="C:\Program Files\LLVM\lib\clang\3.8.0\include" -DBOOST_ROOT="C:\Libraries\boost_1_60_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_60_0\lib64-msvc-14.0" -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_MULTITHREADED=ON -DBoost_USE_STATIC_RUNTIME=ON -DCMAKE_CXX_FLAGS="-DBOOST_ALL_NOLIB /EHsc" -DCMAKE_CXX_FLAGS_DEBUG="/MTd" ..\
```
on Appveyor, but thanks a lot!

**Pull request merged**
