### PR TITLE
Clang support

### PR DESCRIPTION
**Pull request by Manu343726**
As you can see there was an issue regarding POD default-initialization that (correctly) prevented Clang to build your code.

It would be great to add Clang to the CI setup (If there's one).

### CODE REVIEW

**Comment by foonathan** [comment]
Why the anonymous namespace?

**Comment by Manu343726** [comment]
I thought the tag type is an implementation detail, that's why the type was declared inline right?

I could change to a `detail` nested namespace if you prefer.

**Comment by foonathan** [comment]
I didn't do it because it is supposed to be an implementation detail. I did it out of reflex, because otherwise I had a detail type in the documentation... Yeah, I should stop thinking about Doxygen when making my code :D

Detail namespace is fine.

**Comment by Manu343726** [comment]
Done.

**Pull request merged**
